site_name: ziti - MySQL ORM for Node.js
site_author: Alexandre Laurent
site_favicon: images/favicon.png
repo_url: https://github.com/shaoner/ziti
pages:
- Home: 'index.md'
- Guide:
  - Getting started: 'guide/getting-started.md'
  - Using ziti: 'guide/ziti.md'
  - Model: 'guide/model.md'
  - Queries: 'guide/queries.md'
  - Associations: 'guide/associations.md'
  - Model instance: 'guide/instance.md'
- API:
  - ziti: 'api/ziti.md'
  - Model: 'api/model.md'
  - Instance: 'api/instance.md'
  - Query: 'api/query.md'
  - Types: 'api/types.md'
  - Functions: 'api/functions.md'
- About: 'about.md'
theme: readthedocs
extra_css: [ 'style.css' ]
markdown_extensions:
  - mdx_del_ins
