site_name: ziti - MySQL ORM for Node.js
site_author: Alexandre Laurent
site_favicon: favicon.png
repo_url: https://github.com/shaoner/ziti
pages:
- ['index.md', 'Home']
- ['guide/getting-started.md', 'Guide', 'Getting started']
- ['guide/ziti.md', 'Guide', 'Configuring ziti']
- ['guide/model.md', 'Guide', 'Model']
- ['guide/queries.md', 'Guide', 'Queries']
- ['guide/associations.md', 'Guide', 'Associations']
- ['guide/instance.md', 'Guide', 'Model instances']
- ['api/ziti.md', 'API', 'ziti']
- ['api/model.md', 'API', 'Model']
- ['api/instance.md', 'API', 'Instance']
- ['api/types.md', 'API', 'Types']
- ['api/functions.md', 'API', 'Functions']
- ['about.md', 'About']
- ['todo.md', 'TODO']
theme: readthedocs
